android_library(
    name = "edgemlmonitor",
    srcs = glob(
        ["*.java"],
    ),
    manifest = "AndroidManifest.xml",
    visibility = ["//visibility:public"],
    deps = [
        "//edgeml/java/com/edgeml/monitor/env",
        "//edgeml/java/com/edgeml/monitor/hwinfo",
        #        "@maven//:io_opentelemetry_opentelemetry_api",
        #        "@maven//:io_opentelemetry_opentelemetry_context",
        #        "@maven//:io_opentelemetry_opentelemetry_exporter_otlp",
        #        "@maven//:io_opentelemetry_opentelemetry_exporter_otlp_trace",
    ],
)
