android_library(
    name = "framework",
    srcs = glob([
        "*.java",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "//edgeml/cpp/tfbenchmark/jni:tensorflowlite_benchmark_native",
    ],
)
