apiVersion: v1
kind: Service
metadata:
  name: mlexray
  labels:
    app: mlexray
  namespace: mlexray
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mlexray
