android_library(
    name = "hwinfo",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//edgeml/java/com/edgeml/monitor/env",
        "@maven//:androidx_annotation_annotation",
    ],
)
